//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchievementTBL
    {
        public int idAchievement { get; set; }
        public string TitleAchievement { get; set; }
        public int TypeAchievement { get; set; }
        public int Student { get; set; }
        public string infoAchievement { get; set; }
        public System.DateTime DateReceived { get; set; }
    
        public virtual StudentsTBL StudentsTBL { get; set; }
        public virtual TypeAchievementTBL TypeAchievementTBL { get; set; }
    }
}
